config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users
  resources :listings do
     collection do
      get 'search'
    end 
   resources :orders, only: [:new, :create]
   resources :reviews

    member do
      put "like", to: "listings#upvote"
    end

 end
  get 'pages/about'

  get 'pages/contact'

  get'seller'=> "listings#seller"
  get 'sales'=> "orders#sales"
  get 'purchases'=> "orders#purchases"
root'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  is_impressionable
    acts_as_votable
        searchkick suggest: [:name] 


	
	if Rails.env.development?
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  else
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/,
                :storage => :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml"), :path => ":style/:id_filename"

end


 validates :name, :description,  :address, :phone, presence: true 
 validates :price, numericality: { greater_than: 0}
 validates :phone, length: { maximum: 14 }

 validates_attachment_presence :image
 geocoded_by :full_address
  after_validation :geocode

  def full_address
    [address].join(',')
  end 



 belongs_to :user
 has_many :orders
 belongs_to :category
  belongs_to :location
  has_many   :reviews
  has_many :impressions, :as=>:impressionable


 


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy,:upvote]
   before_filter :authenticate_user!, only: [ :seller, :new, :create, :edit, :update, :destroy, :upvote]
   before_filter :check_user, only: [:edit, :update, :destroy]
  impressionist actions: [:show], unique: [:session_hash]
  
  def search
    if params[:search].present?
      @listings= Listing.search(params[:search])
    else
      @listings = Listing.all
    end
  end

 def seller
      @listings = Listing.where(user: current_user).paginate(:page => params[:page], :per_page => 4).order("created_at DESC")

 
  end 
  
  # GET /listings
  # GET /listings.json
  def index

  #visitor_latitude= 0.318383
  #visitor_longitude= 32.574706

  
  @listings = Listing.paginate(:page => params[:page], :per_page => 8).order("created_at DESC")
 
  
  

      

  if params[:category].present?
    category_id = Category.find_by(name: params[:category]).try(:id)
    @listings = @listings.where(category_id: category_id) if category_id
  end

  if params[:location].present?
    location_id = Location.find_by(name: params[:location]).try(:id)
    @listings = @listings.where(location_id: location_id) if location_id
  end
   
 
end
 

  # GET /listings/1
  # GET /listings/1.json
  def show
     #visitor_latitude=request.location.latitude
#visitor_longitude=request.location.longitude
#visitor_latitude= 0.318383
#visitor_longitude= 32.574706


      if @listing.reviews.blank?
      @average_review = 0
    else
      @average_review = @listing.reviews.average(:rating).round(2)
    end

     @listings = Listing.find(params[:id])
  impressionist(@listings)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @categories = Category.all.map{|c| [c.name, c.id]}
   @locations= Location.all.map{|c| [c.name, c.id]}
  end 

  # GET /listings/1/edit
  def edit
     @categories = Category.all.map{|c| [c.name, c.id]}
      @locations= Location.all.map{|c| [c.name, c.id]}
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
   
    @listing.category_id = params[:category_id]
    
      @listing.location_id = params[:location_id]

   
     
    @listing.user_id = current_user.id


    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      @listing.category_id = params[:category_id]
        @listing.location_id = params[:location_id]

      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote 
    @listing.upvote_by current_user
    redirect_to :back

  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image, :address, :phone, :category_id, :location_id)
    end
    def check_user
       if current_user != @listing.user
          redirect_to root_url, alert: "Sorry, this ad belongs to someone else"
    end 
    end 
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
  <%= select_tag(:location_id,options_for_select(@locations), :prompt=>"select your location")%>
  </div>
  <div class="form-group">
<%= select_tag(:category_id,options_for_select(@categories), :prompt=>"select a category")%>
</div>
  <div class="form-group">

    <%= f.label :name %><br>
    <%= f.text_field :name , placeholder: "name", class: "form-control border-radius-small" %>
  </div>
<div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,  placeholder: "Item description",class: "form-control border-radius-small"%>
  </div>
 <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, placeholder: "Item price", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, placeholder: "Item image",class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, placeholder: "Address", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, placeholder: "Phone", class: "form-control" ,style:" width: 280px;height: 30px"%>
  </div>
  <div class="form-group">

    <%= f.submit "Create Ad", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="edit-book-form">

<h1>Editing listing</h1>

<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <%=f.select :location_id,@locations%>
  </div>
  <div class="form-group">
<%=f.select :category_id,@categories%>
</div>
  <div class="form-group">

    <%= f.label :name %><br>
    <%= f.text_field :name , placeholder: "name", class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description ,  placeholder: "Item description",class: "form-control"%>
  </div>
 <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, placeholder: "Item price", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, placeholder: "Item image",class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_area :address, placeholder: "Address", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, placeholder: "Phone", class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>


<%= link_to 'Show', @listing, class: "btn btn-link"%> 
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>
</div>

app/views/listings/index.html.erb
<div class="black">
  <h3 class="current-category" style="color:blue" > <%= params[:category] %></h3>
  <h3 class="current-category" style="color:blue" > <%= params[:location] %></h3>
  <% if @listings.count== 0 %>

  <h3> There are  no Items currently for that category </h3>

  <%else%>


  <div class="row">
   <% @listings.each do |listing| %>
     <div class="col-md-3">
     <div class="thumbnail">
      <%= link_to image_tag(listing.image.url), listing %>
         
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price,:unit => "Fr") %></p>
            
            <p lass="current-category" style="color:blue;">Posted <%=time_ago_in_words(listing.created_at) %> by  <%= listing.user.name%></p>

           

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= listing.name %></h4>
      </div>
      <div class="modal-body">
       
<div class="row">
<div class="col-md-6">
<div class="thumbnail">
<%= image_tag listing.image.url %>
</div>
</div>
<div class="col-md-6">
<h3><%= listing.name %></h3>
<p> <%= number_to_currency(listing.price,:unit => "UGX") %></p>
<p> <%= listing.description %></p>
<p> Call me:<%= listing.phone %></p>
<p> Address:<%= listing.address %></p>
<%= link_to 'Order Now', new_listing_order_path(listing), class: "btn btn-primary" %> |
  
</div>
</div>
 <% if current_user == listing.user %>
<%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %> 
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       
      </div>
    </div>
  </div>
</div>
            </div>
          </div>
       
      </div>
     <%end%>
    
  </div>
</div>
<%end%>

<br>

</div>
<% unless @listings.empty? %>

<nav>
  <ul class="pager">
    <li class="previous " <%= will_paginate @listings%> <span aria-hidden="true">&larr;
   
  </ul>
</nav>
<% end %>

app/views/listings/new.html.erb
<div class="col-md-6">

	<div class="new-book-form">
    <h1 style="color:blue">New Ad</h1>
<%= render 'form' %>
<%= link_to 'Back', listings_path %>
</div>
</div>

app/views/listings/search.html.erb
 <div class="row">
   <% @listings.each do |listing| %>
     <div class="col-md-3">
     <div class="thumbnail">
      <%= link_to image_tag(listing.image.url), listing %>
         
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price,:unit => "USh") %></p>
            
            <p lass="current-category" style="color:blue;">Posted <%=time_ago_in_words(listing.created_at) %> by  <%= listing.user.name%></p>
 </div>
	<% end %>
</div>
</div>
</div>

app/views/listings/seller.html.erb





  

<br>
<div class="black">
<table class = "table table-striped table-bordered table-hover" width="200" height="60">
<tr>
<h1> <%=current_user.name%>  ads </h1>
<th class = "center">Image</th>
    <th class = "center">Name</th>
    <th class = "center">Description</th>
    <th class = "center, info">Price</th>
    <th class = "center">Action</th>
</tr>

 <% @listings.each do |listing| %>
 <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td ><%= number_to_currency(listing.price,:unit => "UGX") %></td>
      <td>
      <div class="btn-group">
           <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
             Action <span class="caret"></span>
           </button>
           <ul class="dropdown-menu" role="menu">
        <li><%= link_to "view", listing, class: "btn btn-link" %></li>
        <li><%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %></li>
        <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
        </ul>
         </div>
      </td>
      </tr>




    <%end%>

    </table>



<br>
  <% if user_signed_in? %>
    <%= link_to 'New Ad', new_listing_path, class: "btn btn-primary" %>   
  <%end%>
</div>

<% unless @listings.empty? %>

<nav>
  <ul class="pager">
    <li class="previous " <%= will_paginate @listings%> <span aria-hidden="true">&larr;
   
  </ul>
</nav>
<% end %>

app/views/listings/show.html.erb
<div class="black">
<div class="row">
<div class="col-md-6">
<br>
<div class="thumbnail">
<%= image_tag @listing.image.url %>
<div class="center"><%=link_to like_listing_path(@listing), method: :put, class: "btn btn-default" do %>
	<span class="glyphicon glyphicon-heart"></span>
	Like
	<%= @listing.get_upvotes.size %>
	   <% end %>
	</div>
</br>
</div>
</div>
<div class="col-md-6">
<div class="book-info">

	<h3 class="book-title"><%= @listing.name %></h3>
	<p > <%= number_to_currency(@listing.price,:unit => "USh") %></p>
	<p class="book-desc"> <%= @listing.description %></p>
	<p class="book-author"> <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-phone-alt"></span> Phone
        </button>:<%= @listing.phone %></p>
	<p class="book-desc"> Address:<%= @listing.address %></p>
	<p class="current-category" style="color:blue" >Location: <%=@listings.location.name %> </p>

	<div class="average-review-rating" data-score=<%=  @average_review %>> Average Rating: </div>
    <p class="current-category" style="color:blue" > Views:<%=@listing.impressionist_count(:filter=>:session_hash) %> <p>

   <p lass="current-category" style="color:#333333;">Posted <%=time_ago_in_words(@listings.created_at) %> by  <%= @listings.user.name%></p>


	<%= link_to 'Order Now', new_listing_order_path(@listing), class: "btn btn-primary" %> 

   
		
</div>
</div>
</div>
</div>
<div class="col-md-6">
<div class="book-info">

<div id="googleMap" style="width:400px;height:380px;">
<P>GET ADDRESS</P>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d127672.28080396666!2d<%=@listings.longitude%>!3d<%=@listings.latitude%>!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sug!4v1461859453680" width="510" height="350" frameborder="1" style="border:1" allowfullscreen></iframe>
</div>
</div>
</div>

<div class="row">
<div class="col-md-4">
<div class="reviews"> 
	<h5 ><%= @listing.reviews.count %>Comment</h5>
	<hr>
	<%= render @listing.reviews.limit(7).order("created_at DESC") %> 
	

	<%= form_for([@listing,@listing.reviews.build]) do |f| %>
  
<div id="rating-form">

<label>Rating</label>
</div>
  <div class="form-group">
   
   <span class="glyphicon glyphicon-user"></span> <%= f.text_area :comment, placeholder: "Write comment", class: "form-control" %>
  </div>
  <div class="form-group ">
    <%= f.submit "Submit ", class: "btn btn-success" %>
  </div>
<% end %>
<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>
	
</div>
</div>
</div>
<br>



  

 <% if current_user == @listing.user %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> 
	<% end %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>
<!-- Button trigger modal -->
<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>