config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users
  resources :listings do
     collection do
      get 'search'
    end 
   resources :orders, only: [:new, :create]
   resources :reviews

    member do
      put "like", to: "listings#upvote"
    end

 end
  get 'pages/about'

  get 'pages/contact'

  get'seller'=> "listings#seller"
  get 'sales'=> "orders#sales"
  get 'purchases'=> "orders#purchases"
root'listings#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_listing 
	 before_action :find_review, only:[:edit, :update, :destroy ]
	 before_action :authenticate_user!, only: [:new, :edit,:create]


	def new 

		@review= Review.new
	end 

	def create 
		@review= Review.new(review_params)
		@review.listing_id = @listing.id
		@review.user_id =  current_user.id

		if @review.save
			redirect_to listing_path(@listing)
		else
			render'new'
		end
	end 

	def edit
		@review = Review.find(params[:id])
	end 
	def update 
		if @review.update(review_params)
				redirect_to listing_path(@listing)
				else
				render'edit'
			end
	end 

	def destroy

		@review.destroy
		redirect_to listing_path(@listing)
	end

	private 


	def review_params

    params.require(:review).permit(:rating, :comment)
	end 
    def find_listing 
    	@listing = Listing.find(params[:listing_id])
    end 

    def find_review
			@review = Review.find(params[:id])

		end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@listing,@listing.reviews.build]) do |f| %>
  <% if @review.errors.any? %>
   <div id="error_explanation" class="alert alert-danger alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="rating-form">

<label>Rating</label>
</div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, placeholder: "Comment", class: "form-control" %>
  </div>
  <div class="form-group ">
    <%= f.submit "Submit ", class: "btn btn-success" %>
  </div>
<% end %>
<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review ">
<p style="color:blue"> <%= review.user.name%></p>
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p class="review-comment"> <%= review.comment %> (Posted <%=time_ago_in_words(review.created_at) %>)</p>






<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>
	  <div class="links btn-group">
<%=link_to "Edit", edit_listing_review_path(review.listing, review),class: "btn btn-custom" %>
<%=link_to "Delete", listing_review_path(review.listing, review), method: :delete, data: {confirm: "Are you sure?"} ,class: "btn btn-custom" %>
</div>
<%end%>
<%end%>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <div class="new-review-form">

<%= form_for([@listing,@review]) do |f| %>
  <% if @review.errors.any? %>
   <div id="error_explanation" class="alert alert-danger alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="rating-form">

<label>Rating</label>
</div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, placeholder: "Comment", class: "form-control" %>
  </div>
  <div class="form-group ">
    <%= f.submit "Review ", class: "btn btn-success" %>
  </div>
<% end %>
</div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>


app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

<h1> New Review</h1>
<%= render 'form' %>

</div>
</div>