config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users
  resources :listings do
     collection do
      get 'search'
    end 
   resources :orders, only: [:new, :create]
   resources :reviews

    member do
      put "like", to: "listings#upvote"
    end

 end
  get 'pages/about'

  get 'pages/contact'

  get'seller'=> "listings#seller"
  get 'sales'=> "orders#sales"
  get 'purchases'=> "orders#purchases"
root'listings#index'

end

app/views/layouts/_footer.html.erb


<nav class="navbar navbar-default navbar-fixed-bottom "  >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">M</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
     <li ><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>

        
  
      </ul>
     

        

          
          





          
          
        <ul class="nav navbar-nav navbar-right"  >

         <%= link_to "Hi!Advertise with us", new_user_registration_path, class: "current-category" %>          
         
           

        

       </ul>
   <!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





app/views/layouts/_header.html.erb


<nav class="navbar navbar-default  "  >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PANGA</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
     <li ><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>

        
  
      </ul>
      <%= form_tag search_listings_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], placeholder: "search ads", class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
        <% end %>

        <ul class="nav navbar-nav navbar-right" >
       
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false">Select category<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                 <% Category.all.each do |category|%>
                <li class="<%='active' if params[:category] == category.name %>" > 
                <%= link_to category.name, listings_path(category: category.name), class: "link" %></li>
                 <%end%>
                  
                
              </ul>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false">Select Location<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                 <% Location.all.each do |location|%>
                <li class="<%='active' if params[:location] == location.name %>" > 
                <%= link_to location.name, listings_path(location: location.name), class: "link" %></li>
                 <%end%>
                  
                
              </ul>

          <% if user_signed_in? %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                 <li><%= link_to "Manage Listings", seller_path %></li>
                  <li><%= link_to "Sales History", sales_path %></li>
                   <li><%= link_to 'New Ad', new_listing_path %> </li>  

                  

                
              </ul>
          </li>

           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Hi!<span class="glyphicon glyphicon-user"></span> <%=current_user.name%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Purchases History", purchases_path %></li>
         

                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                
              </ul>
          </li>





          
          
        <% else %>

          <li > <%= link_to "Hi!Sign Up", new_user_registration_path %></li>
           <li><%= link_to "Sign In", new_user_session_path %></li>
           

        <%end%>

       </ul>
   <!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<marquee >

<div class="id="clockbox" style="text-align: right; text-color:#333333; font:12pt Arial;"">
<script type="text/javascript">
tday=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");
tmonth=new Array("January","February","March","April","May","June","July","August","September","October","November","December");

function GetClock(){
var d=new Date();
var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getYear();
if(nyear<1000) nyear+=1900;
var nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

if(nhour==0){ap=" AM";nhour=12;}
else if(nhour<12){ap=" AM";}
else if(nhour==12){ap=" PM";}
else if(nhour>12){ap=" PM";nhour-=12;}

if(nmin<=9) nmin="0"+nmin;
if(nsec<=9) nsec="0"+nsec;

document.getElementById('clockbox').innerHTML=""+tday[nday]+", "+tmonth[nmonth]+" "+ndate+", "+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
}

window.onload=function(){
GetClock();
setInterval(GetClock,1000);
}
</script>
<div id="clockbox"></div>


</div>
</marquee>
<br>

app/views/layouts/_sidebar.html.erb
<div id="nav">
<p>kim</p>

<div class="col-md-6">


     <li > <%= link_to "Hi!Sign Up", new_user_registration_path %></li>
           <li><%= link_to "Sign In", new_user_session_path %></li>
     
</div>
</div>
</div>
<script >
 $(function(){
    $('#nav').hover(function(){
        $(this).animate({width:'220px'},500);
    },function(){
        $(this).animate({width:'40px'},500);
    }).trigger('mouseleave');
    });
</script>

app/views/layouts/_sidebar1.html.erb


<nav class="navbar navbar-default navbar-fixed-top "  >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Edeal</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
     <li ><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>

        
  
      </ul>

        <ul class="nav navbar-nav navbar-right  navbar-inverse" >
         <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false">All Categories<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                 <% Category.all.each do |category|%>
                <li class="<%='active' if params[:category] == category.name %>" > 
                <%= link_to category.name, listings_path(category: category.name), class: "link" %></li>
                 <%end%>
                  
                
              </ul>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"  aria-expanded="false">All Locations<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                 <% Location.all.each do |location|%>
                <li class="<%='active' if params[:location] == location.name %>" > 
                <%= link_to location.name, listings_path(location: location.name), class: "link" %></li>
                 <%end%>
                  
                
              </ul>

          <% if user_signed_in? %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                 <li><%= link_to "Manage Listings", seller_path %></li>
                  <li><%= link_to "Sales History", sales_path %></li>
                   <li><%= link_to 'New Ad', new_listing_path %> </li>  

                  

                
              </ul>
          </li>

           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" >Hi! <%=current_user.name%> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Purchases History", purchases_path %></li>
         

                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                
              </ul>
          </li>





          
          
        <% else %>

          <li > <%= link_to "Hi!Sign Up", new_user_registration_path %></li>
           <li><%= link_to "Sign In", new_user_session_path %></li>
           

        <%end%>

       </ul>
   <!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<marquee >

<div class="id="clockbox" style="text-align: right; text-color:#333333; font:12pt Arial;"">
<script type="text/javascript">
tday=new Array("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");
tmonth=new Array("January","February","March","April","May","June","July","August","September","October","November","December");

function GetClock(){
var d=new Date();
var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getYear();
if(nyear<1000) nyear+=1900;
var nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

if(nhour==0){ap=" AM";nhour=12;}
else if(nhour<12){ap=" AM";}
else if(nhour==12){ap=" PM";}
else if(nhour>12){ap=" PM";nhour-=12;}

if(nmin<=9) nmin="0"+nmin;
if(nsec<=9) nsec="0"+nsec;

document.getElementById('clockbox').innerHTML=""+tday[nday]+", "+tmonth[nmonth]+" "+ndate+", "+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
}

window.onload=function(){
GetClock();
setInterval(GetClock,1000);
}
</script>
<div id="clockbox"></div>


</div>
</marquee>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edeal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


<%= render 'layouts/header' %>	



<div class="container">
<% flash.each do |name, msg| %>
	    <% if msg.is_a?(String) %>
	      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      </div>
	    <% end %>
	  <% end %>
  <div class="owl-carousel">
    <div class="item" data-merge="1"><h2><img src="../assets/shoes1.jpeg " alt="all star"></h2></div>
    <div class="item" data-merge="2"><h2><img src="../assets/shoes2.jpeg" alt="all star"></h2></div>
    <div class="item" data-merge="1"><h2><img src="../assets/shoes1.jpeg"></h2></div>
    <div class="item" data-merge="3"><h2><img src="../assets/shoes2.jpeg"></h2></div>
    <div class="item" data-merge="6"><h2>6</h2></div>
    <div class="item" data-merge="2"><h2>7</h2></div>
    <div class="item" data-merge="1"><h2>8</h2></div>
    <div class="item" data-merge="3"><h2>9</h2></div>
    <div class="item"><h2>10</h2></div>
    <div class="item"><h2>11</h2></div>
    <div class="item" data-merge="2"><h2>12</h2></div>
    <div class="item"><h2>13</h2></div>
    <div class="item"><h2>14</h2></div>
    <div class="item"><h2>15</h2></div>
</div>

<%= yield %>


</div>


 
</div>

<br>
<br>
<%= render 'layouts/footer' %>
	
</body>

</html>

<script>
  

$('.owl-carousel').owlCarousel({
    items:5,
    loop:true,
    margin:10,
    merge:true,
    autoPlay:true,
    responsive:{
        678:{
            mergeFit:true
        },
        1000:{
            mergeFit:false
        }
    }
});
</script>